### PR TITLE
Switch deprecated JSON to new json

### PR DESCRIPTION
**Pull request by srawlins**

### CODE REVIEW

**Comment by jakemac53** [comment]
cc @natebosch any idea how long before we can replace this with build_resolvers internally?

**Comment by natebosch** [comment]
Ugh, probably once I bite the bullet and spend time on https://github.com/dart-lang/build/issues/1418

**Comment by srawlins** [comment]
Landing #66 first will clean up Travis.

**Comment by jakemac53** [comment]
Ok, I think for now we can accept these changes and roll them internally, but not publish a version on pub.

**Review by jakemac53 — APPROVED** [review]

**Comment by jakemac53** [comment]
@srawlins can you update the travis.yml to use the dev sdk?

**Comment by srawlins** [comment]
That is done in #66.

**Pull request merged**
